Repository OpenAssetIO/OpenAssetIO, pull requests merged in 2021-11, with the labels that each got.

#92 [CI] Add CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: ci

#102 [CI] Add yml section in .editorconfig
  .editorconfig
Labels: ci

#91 [CI] Run `pytest` for Pull Requests
  .github/workflows/test.yml
Labels: ci

#108 [Core] Rename `BaseException` -> `OAIOException`
  python/openassetio/exceptions.py
  python/openassetio/managerAPI/ManagerInterface.py
Labels: api change

#103 [Docs] Continuous deployment of GitHub Pages from `main`
  .github/workflows/docs.yml
  doc/Makefile
  doc/README.md
  doc/deploy.sh
Labels: documentation, ci

#104 [CI] Build docs for Pull Requests to catch markup errors
  .github/workflows/problem-matchers/doxygen.json
  .github/workflows/test.yml
Labels: documentation, ci

#94 [Docs] Misc documentation fixes
  doc/src/EntitySpecMeta.dox
  doc/src/Examples.dox
  doc/src/ForHosts.dox
  doc/src/ForManagers.dox
  doc/src/Glossary.dox
  python/openassetio/hostAPI/Manager.py
  python/openassetio/managerAPI/ManagerInterface.py
Labels: documentation

#98 [Core] Batch manager methods
  CONTRIBUTING.md
  doc/src/Examples.dox
  doc/src/ManagerState.dox
  doc/src/Transactions.dox
  python/openassetio/constants.py
  python/openassetio/hostAPI/Manager.py
  python/openassetio/managerAPI/ManagerInterface.py
  tests/openassetio/hostAPI/test_manager.py
  tests/openassetio/managerAPI/test_managerinterface.py
Labels: documentation, api change

#111 [Docs] Fix broken `@refs` pointing to un-migrated docs
  doc/Doxyfile
  doc/Makefile
  doc/src/ForHosts.dox
  doc/src/ForManagers.dox
  python/openassetio/hostAPI/ManagerFactoryInterface.py
  python/openassetio/pluginSystem/ManagerPlugin.py
  python/openassetio/pluginSystem/PluginSystemManagerFactory.py
Labels: documentation

#112 [CI] Suppress summary output from grep when checking for build errors
  .github/workflows/test.yml
Labels: ci
