Repository OpenAssetIO/OpenAssetIO, pull requests merged in 2022-11, with the labels that each got.

#707 [CI] Update action versions
  .github/bootstrap_platform/action.yml
  .github/workflows/code-quality.yml
  .github/workflows/test.yml
Labels: ci

#710 [Release] Bump version to v1.0.0-alpha.6
  RELEASE_NOTES.md
  pyproject.toml
  resources/openassetio-traitgen/setup.py
Labels: release

#675 [Build] Add CMake metadata to better support downstream projects
  CMakeLists.txt
  cmake/Config.cmake.in
  cmake/DefaultTargetProperties.cmake
  cmake/ThirdParty.cmake
  src/openassetio-core-c/CMakeLists.txt
  src/openassetio-core/CMakeLists.txt
  src/openassetio-python/bridge/CMakeLists.txt
  src/openassetio-python/module/CMakeLists.txt
  tests/openassetio-python/CMakeLists.txt
Labels: build

#633 [Docs] Add DR for project structure refactor
  decisions/DR013-Project-structure.md
Labels: decision record

#723 [CI] Add `OpenAssetIO-Test-CMake` integration test
  .github/workflows/integrations.yml
Labels: ci

#730 [CI] Bump Conan version to 1.54.0
  resources/build/requirements.txt
Labels: ci

#732 [Build] Use `requires` rather than `tool_requires` in conanfile.py
  resources/build/conanfile.py
Labels: build

#733 [Docs] Add missing fields to DR 13
  decisions/DR013-Project-structure.md
Labels: decision record

#744 [Docs] Fix various links in markdown files
  RELEASE_NOTES.md
  SANDBOXED_BUILDS.md
  contributing/CODING_STYLE.md
  contributing/PROCESS.md
Labels: documentation

#748 [CI] Fix Doxygen docs deployment
  .github/workflows/docs.yml
Labels: bug, ci

#750 [Core] Conform Python to C++ method argument names
  src/openassetio-python/module/src/TraitsDataBinding.cpp
  src/openassetio-python/module/src/hostApi/ManagerBinding.cpp
  src/openassetio-python/module/src/log/SeverityFilterBinding.cpp
  src/openassetio-python/module/src/managerApi/ManagerInterfaceBinding.cpp
Labels: Python

#752 [Docs] Add release notes for Python arg renames
  RELEASE_NOTES.md
Labels: documentation

#755 [Build] Split CMake package variables to own file
  CMakeLists.txt
  cmake/Config.cmake.in
  cmake/Variables.cmake.in
Labels: build

#754 [Build] Move setup.py under openassetio-python
  .github/workflows/build-instructions.yml
  .github/workflows/build-wheels.yml
  .github/workflows/code-quality.yml
  .github/workflows/integrations.yml
  RELEASE_NOTES.md
  doc/BUILDING.md
  resources/build/requirements.txt
  src/openassetio-python/pyproject.toml
  src/openassetio-python/setup.py
Labels: build, Python
