Repository OpenAssetIO/OpenAssetIO, pull requests merged in 2022-04, with the labels that each got.

#309 [Build] Cache test requirements locally
  src/openassetio-python/CMakeLists.txt
Labels: bug, build

#306 [Core] Migrate `getRelatedReferences` to use trait sets
  python/openassetio/hostAPI/Manager.py
  python/openassetio/managerAPI/ManagerInterface.py
  tests/openassetio/hostAPI/test_manager.py
Labels: api change, Python

#312 C API for ManagerInterface identifier/displayName
  .clang-tidy
  .github/workflows/code-quality.yml
  BUILDING.md
  CMakeLists.txt
  README.md
  cmake/DefaultTargetProperties.cmake
  doc/Doxyfile
  resources/build/conanfile.txt
  src/CMakeLists.txt
  src/openassetio-core-c/CMakeLists.txt
  src/openassetio-core-c/include/openassetio/c/SimpleString.h
  src/openassetio-core-c/include/openassetio/c/errors.h
  src/openassetio-core-c/include/openassetio/c/managerAPI/ManagerInterface.h
  src/openassetio-core-c/include/openassetio/c/namespace.h
  src/openassetio-core-c/private/errors.hpp
  src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp
  src/openassetio-core-c/private/managerAPI/CManagerInterface.hpp
  src/openassetio-python/CMakeLists.txt
  tests/.clang-tidy
  tests/CMakeLists.txt
  tests/openassetio-core-c/CMakeLists.txt
  tests/openassetio-core-c/main.cpp
  tests/openassetio-core-c/private/errorsTest.cpp
  tests/openassetio-core-c/private/managerAPI/CManagerInterfaceTest.cpp
  tests/python/README.md
  tests/python/conftest.py
  tests/python/openassetio/_core/test_audit.py
  tests/python/openassetio/hostAPI/test_manager.py
  tests/python/openassetio/hostAPI/test_session.py
  tests/python/openassetio/hostAPI/test_terminology.py
  tests/python/openassetio/hostAPI/test_transactions.py
  tests/python/openassetio/managerAPI/test_host.py
  tests/python/openassetio/managerAPI/test_hostsession.py
  tests/python/openassetio/managerAPI/test_managerinterface.py
  tests/python/openassetio/pluginSystem/resources/README.md
  tests/python/openassetio/pluginSystem/resources/pathA/modulePlugin.py
  tests/python/openassetio/pluginSystem/resources/pathB/packagedPlugin/PackagePlugin.py
  tests/python/openassetio/pluginSystem/resources/pathB/packagedPlugin/__init__.py
  tests/python/openassetio/pluginSystem/resources/pathC/modulePlugin.py
  tests/python/openassetio/pluginSystem/resources/symlinkPath/modulePlugin.py
  tests/python/openassetio/pluginSystem/resources/symlinkPath/packagedPlugin
  tests/python/openassetio/pluginSystem/test_pluginsystem.py
  tests/python/openassetio/pluginSystem/test_pluginsystemmanagerfactory.py
  tests/python/openassetio/test/manager/__init__.py
  tests/python/openassetio/test/manager/conftest.py
  tests/python/openassetio/test/manager/resources/fixtures_cliFail.py
  tests/python/openassetio/test/manager/resources/fixtures_cliPass.py
  tests/python/openassetio/test/manager/resources/fixtures_executeSuiteTests.py
  tests/python/openassetio/test/manager/resources/plugins/StubManager.py
  tests/python/openassetio/test/manager/resources/suite_alwaysFail.py
  tests/python/openassetio/test/manager/resources/suite_alwaysPass.py
  tests/python/openassetio/test/manager/resources/suite_executeSuiteTests.py
  tests/python/openassetio/test/manager/test__implementation.py
  tests/python/openassetio/test/manager/test_harness.py
  tests/python/openassetio/test/manager/test_main.py
  tests/python/openassetio/test_imports.py
  tests/python/openassetio/test_log.py
  tests/python/openassetio/test_specification.py
  tests/python/openassetio/test_traits.py
  tests/python/requirements.txt
Labels: C

#322 [Examples] BAL test assert fixes
  resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
Labels: examples

#323 [Examples] Fix unused import in BAL tests
  resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
Labels: examples

#324 Merge `main` into `feature/181-coreCppBuild`
  README.md
  contributing/USER_PERSONAS.md
  decisions/DR007-Hierarchical-or-compositional-traits-for-specifications.md
  decisions/DR008-Unify-the-entity-data-model.md
  resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
Labels: merge

#314 [CI] Add check to ensure ASWF docker builds work
  .github/workflows/build-instructions.yml
Labels: ci

#320 [Docs] Add doc for basic C API design choices
  contributing/C_API.md
Labels: documentation, C

#321 [Doc] Fix `pip` `requirements.txt` path in build instructions
  BUILDING.md
  tests/python/openassetio/test/manager/resources/plugins/StubManager.py
Labels: documentation, build

#316 [Core] Migrate `preflight` to use trait sets
  doc/src/Examples.dox
  doc/src/Thumbnails.dox
  python/openassetio/hostAPI/Manager.py
  python/openassetio/managerAPI/ManagerInterface.py
  tests/python/openassetio/hostAPI/test_manager.py
Labels: api change, Python

#326 [Lint] Lint C/C++ test directory
  .clang-tidy
  CMakeLists.txt
  CPPLINT.cfg
  cmake/StaticAnalyzers.cmake
  src/CPPLINT.cfg
  tests/openassetio-core-c/private/errorsTest.cpp
  tests/openassetio-core-c/private/managerAPI/CManagerInterfaceTest.cpp
Labels: ci, C++, C

#336 [Core] StringView C API
  src/openassetio-core-c/include/openassetio/c/SimpleString.h
  src/openassetio-core-c/include/openassetio/c/StringView.h
  src/openassetio-core-c/include/openassetio/c/managerAPI/ManagerInterface.h
  src/openassetio-core-c/private/StringView.hpp
  src/openassetio-core-c/private/errors.hpp
  src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp
  tests/openassetio-core-c/CMakeLists.txt
  tests/openassetio-core-c/private/StringViewReporting.hpp
  tests/openassetio-core-c/private/StringViewTest.cpp
  tests/openassetio-core-c/private/errorsTest.cpp
  tests/openassetio-core-c/private/managerAPI/CManagerInterfaceTest.cpp
Labels: C

#329 [Core] Validate specification trait sets passed to `register`
  python/openassetio/hostAPI/Manager.py
  tests/python/openassetio/hostAPI/test_manager.py
Labels: Python

#350 [Core] Remove pure-python `Specification` implementation
  doc/src/EntitySpecMeta.dox
  doc/src/Examples.dox
  doc/src/ForHosts.dox
  doc/src/ForManagers.dox
  doc/src/Glossary.dox
  python/openassetio/Context.py
  python/openassetio/Specification.py
  python/openassetio/SpecificationFactory.py
  python/openassetio/Trait.py
  python/openassetio/__init__.py
  python/openassetio/hostAPI/Manager.py
  python/openassetio/managerAPI/ManagerInterface.py
  python/openassetio/specifications.py
  python/openassetio/test/manager/_implementation.py
  python/openassetio/test/manager/harness.py
  python/openassetio/test/manager/specifications.py
  python/openassetio/test/specifications.py
  resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
  tests/python/openassetio/hostAPI/test_manager.py
  tests/python/openassetio/hostAPI/test_session.py
  tests/python/openassetio/managerAPI/test_host.py
  tests/python/openassetio/test/manager/conftest.py
  tests/python/openassetio/test/manager/resources/suite_executeSuiteTests.py
  tests/python/openassetio/test/manager/test__implementation.py
  tests/python/openassetio/test_imports.py
  tests/python/openassetio/test_specification.py
  tests/python/openassetio/test_trait.py
  tests/python/openassetio/test_traits.py
Labels: api change, Python

#330 [Core] Add InfoDictionary type(def) with initial C API
  src/openassetio-core-c/CMakeLists.txt
  src/openassetio-core-c/include/openassetio/c/InfoDictionary.h
  src/openassetio-core-c/include/openassetio/c/errors.h
  src/openassetio-core-c/include/openassetio/c/managerAPI/ManagerInterface.h
  src/openassetio-core-c/private/InfoDictionary.cpp
  src/openassetio-core-c/private/errors.hpp
  src/openassetio-core-c/private/handles.hpp
  src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp
  src/openassetio-core/include/openassetio/InfoDictionary.hpp
  src/openassetio-core/include/openassetio/specification/Specification.hpp
  src/openassetio-core/include/openassetio/trait/BlobTrait.hpp
  src/openassetio-core/include/openassetio/trait/property.hpp
  src/openassetio-core/include/openassetio/typedefs.hpp
  src/openassetio-core/trait/BlobTrait.cpp
  src/openassetio-python/trait/BlobTraitBinding.cpp
  tests/openassetio-core-c/CMakeLists.txt
  tests/openassetio-core-c/private/InfoDictionaryTest.cpp
  tests/openassetio-core-c/private/errorsTest.cpp
  tests/openassetio-core-c/private/handlesTest.cpp
  tests/openassetio-core-c/private/managerAPI/CManagerInterfaceTest.cpp
Labels: C++, C

#333 [Core] C API InfoDictionary upsert
  src/openassetio-core-c/include/openassetio/c/InfoDictionary.h
  src/openassetio-core-c/private/InfoDictionary.cpp
  tests/openassetio-core-c/private/InfoDictionaryTest.cpp
Labels: C

#334 [Core] C API InfoDictionary basic introspection
  src/openassetio-core-c/include/openassetio/c/InfoDictionary.h
  src/openassetio-core-c/private/InfoDictionary.cpp
  src/openassetio-core/include/openassetio/typedefs.hpp
  tests/openassetio-core-c/private/InfoDictionaryTest.cpp
Labels: C

#358 [Core] Remove `BlobTrait`
  resources/perftest/perftest.cpp
  src/openassetio-core/CMakeLists.txt
  src/openassetio-core/include/openassetio/trait/BlobTrait.hpp
  src/openassetio-core/include/openassetio/trait/TraitBase.hpp
  src/openassetio-core/trait/BlobTrait.cpp
  src/openassetio-python/CMakeLists.txt
  src/openassetio-python/_openassetio.cpp
  src/openassetio-python/_openassetio.hpp
  src/openassetio-python/trait/BlobTraitBinding.cpp
  tests/python/openassetio/test_specification.py
  tests/python/openassetio/test_traits.py
Labels: api change, C++, Python

#353 [Core] Migrate `ManagerInterface` `info` method to C++
  doc/src/Examples.dox
  python/openassetio/hostAPI/ManagerFactoryInterface.py
  python/openassetio/managerAPI/ManagerInterface.py
  python/openassetio/pluginSystem/PluginSystemManagerFactory.py
  src/openassetio-core-c/include/openassetio/c/InfoDictionary.h
  src/openassetio-core-c/include/openassetio/c/managerAPI/ManagerInterface.h
  src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp
  src/openassetio-core-c/private/managerAPI/CManagerInterface.hpp
  src/openassetio-core/include/openassetio/InfoDictionary.hpp
  src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp
  src/openassetio-core/managerAPI/ManagerInterface.cpp
  src/openassetio-python/managerAPI/ManagerInterfaceBinding.cpp
  tests/openassetio-core-c/private/managerAPI/CManagerInterfaceTest.cpp
  tests/python/openassetio/managerAPI/test_managerinterface.py
Labels: C++, C
