Repository OpenAssetIO/OpenAssetIO, pull requests merged in 2022-09, with the labels that each got.

#605 [Core] Ensure `resolve` callback implementation can use trait views on the provided trait data
  RELEASE_NOTES.md
  src/openassetio-core/include/openassetio/hostApi/Manager.hpp
  src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
Labels: bug, C++

#606 [Tests] Assert Manager methods implemented once
  tests/python/conftest.py
  tests/python/openassetio/hostApi/test_manager.py
  tests/python/openassetio/managerApi/test_managerinterface.py
Labels: test

#601 [Core] Migrate `preflight` and `register` to C++
  RELEASE_NOTES.md
  doc/src/ForManagers.dox
  doc/src/Glossary.dox
  python/openassetio/hostApi/Manager.py
  python/openassetio/managerApi/ManagerInterface.py
  src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.cpp
  src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.hpp
  src/openassetio-core/hostApi/Manager.cpp
  src/openassetio-core/include/openassetio/BatchElementError.hpp
  src/openassetio-core/include/openassetio/Context.hpp
  src/openassetio-core/include/openassetio/hostApi/Manager.hpp
  src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
  src/openassetio-python/module/hostApi/ManagerBinding.cpp
  src/openassetio-python/module/managerApi/ManagerInterfaceBinding.cpp
  tests/openassetio-core-c/private/hostApi/ManagerTest.cpp
  tests/python/openassetio/hostApi/test_manager.py
Labels: C++

#614 [CI] Use Ninja CMake generator
  .github/workflows/code-quality.yml
  .github/workflows/test.yml
Labels: ci

#617 [Docs] Fix CMake `project` HOMEPAGE_URL
  CMakeLists.txt
Labels: documentation

#620 [Core] Fix `RetainPyArgs` for const ref args
  RELEASE_NOTES.md
  src/openassetio-python/module/PyRetainingSharedPtr.hpp
  tests/openassetio-python/PyRetainingSharedPtrTest.cpp
  tests/python/openassetio_test/test_PyRetainingSharedPtr.py
Labels: bug, Python

#621 [CI] Add ccache to speed up linter/sanitizer build
  .github/workflows/code-quality.yml
  .github/workflows/test.yml
  resources/build/bootstrap-ubuntu-20.04.sh
Labels: ci

#625 Misc Docs fixes
  doc/src/Examples.dox
  resources/examples/manager/BasicAssetLibrary/tests/test_bal.py
  resources/examples/manager/SampleAssetManager/tests/test_sam_apiCompliance.py
Labels: documentation

#631 [Release] Bump version to 1.0.0-alpha.4
  RELEASE_NOTES.md
  resources/codegen/setup.py
  setup.py
Labels: release

#619 Support `ctest --parallel`
  .github/workflows/build-instructions.yml
  .github/workflows/code-quality.yml
  .github/workflows/test.yml
  CMakeLists.txt
  README.md
  cmake/ThirdParty.cmake
  contributing/CODING_STANDARDS.md
  src/openassetio-python/module/CMakeLists.txt
  tests/CMakeLists.txt
  tests/openassetio-core-c/CMakeLists.txt
  tests/openassetio-core/CMakeLists.txt
  tests/openassetio-python/CMakeLists.txt
Labels: ci, test, build

#637 [CI] Bump `conan` version to `1.52.0`
  resources/build/requirements.txt
Labels: ci

#636 [Docs] Update `CODE_REVIEWS.md` to cover release notes check
  contributing/CODE_REVIEWS.md
Labels: documentation

#639 Nodiscard attribute on factory make methods
  RELEASE_NOTES.md
  src/openassetio-core/include/openassetio/TraitsData.hpp
  src/openassetio-core/include/openassetio/hostApi/Manager.hpp
  src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp
  src/openassetio-core/include/openassetio/managerApi/HostSession.hpp
Labels: C++

#634 [Examples] Add `simpleResolver` CLI host example
  RELEASE_NOTES.md
  resources/examples/host/simpleResolver/README.md
  resources/examples/host/simpleResolver/bal_animals.json
  resources/examples/host/simpleResolver/bal_animals_openassetio_config.toml
  resources/examples/host/simpleResolver/simpleResolver.py
  resources/examples/host/simpleResolver/test_simpleResolver.py
Labels: examples

#642 [Examples] Add note on runtime requirements to `simpleResolver.py` docs
  resources/examples/host/simpleResolver/README.md
Labels: examples
