Repository OpenAssetIO/OpenAssetIO, pull requests merged in 2022-01, with the labels that each got.

#151 [Core] Misc `Specification` fixes
  python/openassetio/Specification.py
  python/openassetio/SpecificationFactory.py
  python/openassetio/_core/objects.py
  tests/openassetio/test_specification.py
Labels: bug, api change

#165 [Tests] Remove code duplication
  tests/conftest.py
  tests/openassetio/_core/test_audit.py
  tests/openassetio/test_imports.py
Labels: test

#167 [CI] Ensure doc build errors fail checks
  .github/workflows/test.yml
Labels: ci

#168 [Docs] Add notes on doxygen formatting for method params
  CONTRIBUTING.md
Labels: documentation

#171 [CI] Use `TheFoundryVisionmongers` registry for docs Docker image
  .github/workflows/docs.yml
  .github/workflows/test.yml
Labels: documentation, ci

#174 The great `pylint` cleanup - Part XII - a journeys end
  .github/workflows/code-quality.yml
  tests/openassetio/pluginSystem/test_pluginsystemmanagerfactory.py
Labels: ci

#185 [Build] Initial CMake build/install config
  .clang-format
  .editorconfig
  .gitignore
  CMakeLists.txt
  cmake/CompilerWarnings.cmake
  cmake/Config.cmake.in
  cmake/DefaultTargetProperties.cmake
  src/CMakeLists.txt
  src/include/openassetio/managerAPI/ManagerInterface.hpp
  src/openassetio/managerAPI/ManagerInterface.cpp
Labels: wip, C++, build

#186 [Docs] Add extended documentation for the manager test harness
  doc/src/ForManagers.dox
  doc/src/Testing.dox
  python/openassetio/test/__init__.py
  python/openassetio/test/manager/__init__.py
  python/openassetio/test/manager/_implementation.py
  python/openassetio/test/manager/apiComplianceSuite.py
  python/openassetio/test/manager/harness.py
Labels: documentation

#190 [Docs] Add development process guides
  README.md
  contributing/CODE_REVIEWS.md
  contributing/CODING_STANDARDS.md
  contributing/COMMITS.md
  contributing/PROCESS.md
  contributing/PULL_REQUESTS.md
Labels: documentation

#198 [Docs] Fix links in `PROCESS.md`
  contributing/PROCESS.md
Labels: documentation

#192 [Build] Initial skeleton Python bindings
  .github/workflows/test.yml
  CMakeLists.txt
  cmake/DefaultTargetProperties.cmake
  cmake/ThirdParty.cmake
  python/openassetio/managerAPI/ManagerInterface.py
  src/CMakeLists.txt
  src/openassetio-core/CMakeLists.txt
  src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp
  src/openassetio-core/managerAPI/ManagerInterface.cpp
  src/openassetio-python/CMakeLists.txt
  src/openassetio-python/_openassetio.cpp
  src/openassetio/managerAPI/ManagerInterface.cpp
  tests/openassetio/hostAPI/test_manager.py
Labels: C++, build

#202 [Docs] Add notes on currently supported platforms
  README.md
Labels: documentation
