Repository OpenAssetIO/OpenAssetIO, pull requests merged in 2022-10, with the labels that each got.

#647 [Docs] Clarify terminology in `USER_PERSONAS.md`
  contributing/USER_PERSONAS.md
Labels: documentation

#649 Decouple CMake from Python somewhat
  .github/workflows/build-instructions.yml
  BUILDING.md
  CMakeLists.txt
  CMakePresets.json
  README.md
  RELEASE_NOTES.md
  cmake/ThirdParty.cmake
  doc/RELEASE_NOTES.md
  resources/codegen/tests/test___main__.py
  setup.cfg
  setup.py
  src/openassetio-python/CMakeLists.txt
  src/openassetio-python/module/CMakeLists.txt
  tests/CMakeLists.txt
  tests/openassetio-python/CMakeLists.txt
Labels: test, build

#663 Add setup.py that builds Python extension
  .github/bootstrap_platform/action.yml
  .github/workflows/build-instructions.yml
  .github/workflows/code-quality.yml
  .github/workflows/test.yml
  CMakePresets.json
  README.md
  RELEASE_NOTES.md
  pyproject.toml
  resources/build/bootstrap-windows-2019.bat
  resources/build/conanfile.py
  resources/build/conanfile.txt
  setup.py
  src/openassetio-core/CMakeLists.txt
  src/openassetio-python/bridge/CMakeLists.txt
  src/openassetio-python/module/CMakeLists.txt
Labels: build

#671 [CI] Re-enable macOS CI runs
  .github/workflows/build-instructions.yml
  .github/workflows/test.yml
Labels: ci

#680 Bump CI runners to macOS-11
  .github/workflows/build-instructions.yml
  .github/workflows/build-wheels.yml
  .github/workflows/test.yml
  CMakeLists.txt
  resources/build/bootstrap-macos-11.sh
Labels: ci

#678 [Release] Bump version to 1.0.0-alpha.5
  RELEASE_NOTES.md
  pyproject.toml
  resources/codegen/setup.py
Labels: release

#670 [CI] Enable Dependabot tracking of GitHub Action versions
  .github/dependabot.yml
Labels: on hold, ci

#695 [CI] Populate cache on push to main/feature branches
  .github/workflows/populate-cache.yml
Labels: ci
