Repository OpenAssetIO/OpenAssetIO, pull requests merged in 2022-05, with the labels that each got.

#363 [Build] Allow python venv build without tests
  .github/workflows/build-instructions.yml
  CMakeLists.txt
  README.md
  src/openassetio-python/CMakeLists.txt
Labels: build

#362 [Docs] Improve main UML Class diagram wording
  doc/src/MainPage.dox
Labels: documentation

#360 [Core] Minimal Manager C++ implementation
  pyproject.toml
  python/openassetio/__init__.py
  python/openassetio/hostAPI/Manager.py
  src/openassetio-core/CMakeLists.txt
  src/openassetio-core/hostAPI/Manager.cpp
  src/openassetio-core/include/openassetio/hostAPI/Manager.hpp
  src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp
  src/openassetio-core/include/openassetio/typedefs.hpp
  src/openassetio-python/CMakeLists.txt
  src/openassetio-python/_openassetio.cpp
  src/openassetio-python/_openassetio.hpp
  src/openassetio-python/hostAPI/ManagerBinding.cpp
  tests/python/conftest.py
  tests/python/openassetio/hostAPI/test_manager.py
  tests/python/openassetio/hostAPI/test_session.py
  tests/python/openassetio/hostAPI/test_terminology.py
  tests/python/openassetio/hostAPI/test_transactions.py
Labels: C++, Python

#249 [Docs] Update documentation to cover the use of traits
  README.md
  doc/src/EntitiesTraitsSpecifications.dox
  doc/src/EntitySpecMeta.dox
  doc/src/Examples.dox
  doc/src/ForHosts.dox
  doc/src/ForManagers.dox
  doc/src/Glossary.dox
  doc/src/MainPage.dox
  doc/src/Thumbnails.dox
  python/openassetio/hostAPI/Manager.py
  python/openassetio/managerAPI/ManagerInterface.py
  python/openassetio/test/manager/apiComplianceSuite.py
  src/openassetio-core/include/openassetio/specification/Specification.hpp
  src/openassetio-core/include/openassetio/trait/property.hpp
Labels: documentation

#366 [Build] Reinstate basic macOS build support
  cmake/DefaultTargetProperties.cmake
  src/openassetio-python/CMakeLists.txt
  tests/openassetio-core-c/CMakeLists.txt
Labels: build

#374 [Docs] Add best practices badge
  README.md
Labels: documentation

#367 [Core] Allow lazy trait population
  .editorconfig
  python/openassetio/Trait.py
  resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
  src/openassetio-core/include/openassetio/specification/Specification.hpp
  src/openassetio-core/include/openassetio/trait/TraitBase.hpp
  src/openassetio-core/specification/Specification.cpp
  src/openassetio-python/specification/SpecificationBinding.cpp
  tests/python/openassetio/test_specification.py
  tests/python/openassetio/test_trait.py
Labels: api change, C++, Python

#372 [Core] C API for Manager
  src/openassetio-core-c/CMakeLists.txt
  src/openassetio-core-c/include/openassetio/c/hostAPI/Manager.h
  src/openassetio-core-c/include/openassetio/c/managerAPI/CManagerInterface.h
  src/openassetio-core-c/include/openassetio/c/managerAPI/ManagerInterface.h
  src/openassetio-core-c/private/InfoDictionary.cpp
  src/openassetio-core-c/private/handles/Converter.hpp
  src/openassetio-core-c/private/handles/InfoDictionary.hpp
  src/openassetio-core-c/private/handles/hostAPI/Manager.hpp
  src/openassetio-core-c/private/handles/managerAPI/ManagerInterface.hpp
  src/openassetio-core-c/private/hostAPI/Manager.cpp
  src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp
  src/openassetio-core-c/private/managerAPI/CManagerInterfaceAdapter.hpp
  src/openassetio-core/include/openassetio/typedefs.hpp
  tests/openassetio-core-c/CMakeLists.txt
  tests/openassetio-core-c/private/InfoDictionaryTest.cpp
  tests/openassetio-core-c/private/StringViewReporting.hpp
  tests/openassetio-core-c/private/handlesTest.cpp
  tests/openassetio-core-c/private/hostAPI/ManagerTest.cpp
  tests/openassetio-core-c/private/managerAPI/CManagerInterfaceAdapterTest.cpp
  tests/openassetio-core-c/private/managerAPI/MockManagerInterfaceSuite.hpp
Labels: C

#375 [Docs] Add change log process documentation
  contributing/CHANGES.md
  contributing/PROCESS.md
Labels: documentation

#380 Update GitHub org references
  .github/workflows/test.yml
  README.md
  contributing/CHANGES.md
  contributing/PROCESS.md
  decisions/DR001-Python-code-style.md
  decisions/DR002-Getter-method-naming.md
  decisions/DR003-ManagerInterface-method-naming.md
  decisions/DR008-Unify-the-entity-data-model.md
  doc/Makefile
  doc/README.md
  doc/src/ForManagers.dox
  doc/src/MainPage.dox
  python/openassetio/__init__.py
  resources/examples/manager/BasicAssetLibrary/schema.json
  resources/examples/manager/BasicAssetLibrary/tests/resources/library_apiComplianceSuite.json
  resources/examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py
  resources/examples/manager/SampleAssetManager/python/SampleAssetManager/__init__.py
Labels: documentation, build

#382 [CI] Enable macOS in test matrix
  .github/workflows/test.yml
  BUILDING.md
  cmake/ThirdParty.cmake
  resources/build/bootstrap-macos-10.15.sh
Labels: ci

#385 Merge `main` into `feature/181-coreCppBuild`
  .github/workflows/test.yml
  README.md
  contributing/CHANGES.md
  contributing/PROCESS.md
  decisions/DR001-Python-code-style.md
  decisions/DR002-Getter-method-naming.md
  decisions/DR003-ManagerInterface-method-naming.md
  decisions/DR008-Unify-the-entity-data-model.md
  doc/Makefile
  doc/README.md
  doc/src/ForManagers.dox
  doc/src/MainPage.dox
  python/openassetio/__init__.py
  resources/examples/manager/BasicAssetLibrary/schema.json
  resources/examples/manager/BasicAssetLibrary/tests/resources/library_apiComplianceSuite.json
  resources/examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py
Labels: merge

#386 Add `RELEASE_NOTES.md`
  RELEASE_NOTES.md
  contributing/CHANGES.md
  contributing/PROCESS.md
  doc/README.md
  doc/RELEASE_NOTES.md
Labels: documentation

#387 Initial alpha release
  CMakeLists.txt
  RELEASE_NOTES.md
  contributing/COMMITS.md
  setup.py
  src/openassetio-python/CMakeLists.txt
Labels: release

#373 Split `Specification` into views + data
  RELEASE_NOTES.md
  doc/src/Examples.dox
  doc/src/Glossary.dox
  doc/src/Transactions.dox
  python/openassetio/Context.py
  python/openassetio/SpecificationBase.py
  python/openassetio/Trait.py
  python/openassetio/__init__.py
  python/openassetio/_core/audit.py
  python/openassetio/hostAPI/Manager.py
  python/openassetio/managerAPI/ManagerInterface.py
  python/openassetio/test/manager/_implementation.py
  python/openassetio/test/manager/harness.py
  python/openassetio/test/specifications.py
  resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
  resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
  resources/perftest/perftest.cpp
  src/openassetio-core/CMakeLists.txt
  src/openassetio-core/TraitsData.cpp
  src/openassetio-core/include/openassetio/TraitsData.hpp
  src/openassetio-core/include/openassetio/specification/Specification.hpp
  src/openassetio-core/include/openassetio/trait/TraitBase.hpp
  src/openassetio-core/include/openassetio/trait/property.hpp
  src/openassetio-core/include/openassetio/typedefs.hpp
  src/openassetio-python/CMakeLists.txt
  src/openassetio-python/TraitsDataBinding.cpp
  src/openassetio-python/_openassetio.cpp
  src/openassetio-python/_openassetio.hpp
  tests/CMakeLists.txt
  tests/openassetio-core/CMakeLists.txt
  tests/openassetio-core/main.cpp
  tests/openassetio-core/trait/TraitBaseTest.cpp
  tests/python/conftest.py
  tests/python/openassetio/hostAPI/test_manager.py
  tests/python/openassetio/hostAPI/test_session.py
  tests/python/openassetio/managerAPI/test_host.py
  tests/python/openassetio/test/manager/conftest.py
  tests/python/openassetio/test/manager/resources/suite_executeSuiteTests.py
  tests/python/openassetio/test/manager/test__implementation.py
  tests/python/openassetio/test_imports.py
  tests/python/openassetio/test_specification.py
  tests/python/openassetio/test_specificationbase.py
  tests/python/openassetio/test_trait.py
  tests/python/openassetio/test_traitsdata.py
Labels: documentation, api change, C++, Python

#394 [Build] Better `clean`ing
  CMakeLists.txt
  src/openassetio-python/CMakeLists.txt
Labels: build

#393 Support un-versioned `clang-tidy`
  BUILDING.md
  RELEASE_NOTES.md
  cmake/StaticAnalyzers.cmake
Labels: build

#397 [Docs] Update release notes with `clean` fixes
  RELEASE_NOTES.md
Labels: documentation

#402 Refactor bootstrap scripts and bump conan version to `1.48.1`
  .github/workflows/code-quality.yml
  .github/workflows/test.yml
  RELEASE_NOTES.md
  resources/build/Vagrantfile
  resources/build/bootstrap-macos-10.15.sh
  resources/build/bootstrap-ubuntu-20.04.sh
  resources/build/bootstrap-windows-2019.bat
  resources/build/requirements.txt
Labels: ci, build

#403 Disable `fail-fast` for CI
  .github/workflows/test.yml
Labels: ci

#396 [Build] Fix C headers to assume C compiler
  RELEASE_NOTES.md
  src/openassetio-core-c/include/openassetio/c/InfoDictionary.h
  src/openassetio-core-c/include/openassetio/c/StringView.h
Labels: build, C

#400 Add CMake presets
  .github/workflows/code-quality.yml
  .github/workflows/test.yml
  BUILDING.md
  CMakePresets.json
  RELEASE_NOTES.md
Labels: build

#404 [Docs] `RELEASE_NOTES.md` tidying
  RELEASE_NOTES.md
Labels: documentation

#410 `README.md` updates
  README.md
Labels: documentation

#405 Rename traits-related methods/vars to "traitSet"
  RELEASE_NOTES.md
  doc/src/Examples.dox
  python/openassetio/SpecificationBase.py
  python/openassetio/hostAPI/Manager.py
  python/openassetio/test/manager/apiComplianceSuite.py
  python/openassetio/test/manager/specifications.py
  python/openassetio/test/specifications.py
  resources/perftest/perftest.cpp
  src/openassetio-core/TraitsData.cpp
  src/openassetio-core/include/openassetio/TraitsData.hpp
  src/openassetio-python/TraitsDataBinding.cpp
  tests/python/openassetio/test/manager/resources/suite_executeSuiteTests.py
  tests/python/openassetio/test_specificationbase.py
  tests/python/openassetio/test_trait.py
  tests/python/openassetio/test_traitsdata.py
Labels: api change, C++, Python

#411 [Docs] Refer to correct default location of `dist`
  BUILDING.md
  README.md
Labels: documentation

#412 [Core] Decouple symbol namespace version from release version
  RELEASE_NOTES.md
  doc/Doxyfile
  doc/Makefile
  src/openassetio-core-c/include/openassetio/c/namespace.h
  src/openassetio-core-c/private/StringView.hpp
  src/openassetio-core-c/private/errors.hpp
  src/openassetio-core-c/private/handles/Converter.hpp
  src/openassetio-core-c/private/handles/InfoDictionary.hpp
  src/openassetio-core-c/private/handles/hostAPI/Manager.hpp
  src/openassetio-core-c/private/handles/managerAPI/ManagerInterface.hpp
  src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp
  src/openassetio-core-c/private/managerAPI/CManagerInterfaceAdapter.hpp
  src/openassetio-core/CMakeLists.txt
  src/openassetio-core/TraitsData.cpp
  src/openassetio-core/hostAPI/Manager.cpp
  src/openassetio-core/include/openassetio/InfoDictionary.hpp
  src/openassetio-core/include/openassetio/TraitsData.hpp
  src/openassetio-core/include/openassetio/hostAPI/Manager.hpp
  src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp
  src/openassetio-core/include/openassetio/trait/TraitBase.hpp
  src/openassetio-core/include/openassetio/trait/property.hpp
  src/openassetio-core/include/openassetio/typedefs.hpp
  src/openassetio-core/managerAPI/ManagerInterface.cpp
  src/openassetio-python/managerAPI/ManagerInterfaceBinding.cpp
  tests/openassetio-core-c/private/managerAPI/MockManagerInterfaceSuite.hpp
Labels: api change, C++, C

#413 [Build] `OPENASSETIO_PYTHON_PIP_TIMEOUT` CMake option
  CMakeLists.txt
  RELEASE_NOTES.md
  src/openassetio-python/CMakeLists.txt
Labels: build

#420 Enable `OPENASSETIO_BUILD_PERFTEST` for all-targets builds
  CMakePresets.json
  resources/perftest/perftest.cpp
Labels: build
