Repository OpenAssetIO/OpenAssetIO, pull requests merged in 2023-05, with the labels that each got.

#922 [Core] Add Ptr alias members to classes
  RELEASE_NOTES.md
  doc/contributing/CODING_STANDARDS.md
  src/openassetio-core/include/openassetio/Context.hpp
  src/openassetio-core/include/openassetio/TraitsData.hpp
  src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp
  src/openassetio-core/include/openassetio/hostApi/Manager.hpp
  src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp
  src/openassetio-core/include/openassetio/hostApi/ManagerImplementationFactoryInterface.hpp
  src/openassetio-core/include/openassetio/log/ConsoleLogger.hpp
  src/openassetio-core/include/openassetio/log/LoggerInterface.hpp
  src/openassetio-core/include/openassetio/log/SeverityFilter.hpp
  src/openassetio-core/include/openassetio/managerApi/Host.hpp
  src/openassetio-core/include/openassetio/managerApi/HostSession.hpp
  src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
  src/openassetio-core/include/openassetio/managerApi/ManagerStateBase.hpp
  src/openassetio-core/include/openassetio/typedefs.hpp
  src/openassetio-core/tests/CMakeLists.txt
  src/openassetio-core/tests/typedefsTest.cpp
Labels: C++

#932 Move `getRelated` refactor release notes into feature-specific section
  RELEASE_NOTES.md
Labels: feature branch

#930 [Release] Bump version to version v1.0.0-alpha.11
  RELEASE_NOTES.md
  src/openassetio-python/pyproject.toml
Labels: release

#933 Merge `main` into related ref feature branch
  RELEASE_NOTES.md
  doc/contributing/CODING_STANDARDS.md
  src/openassetio-core/include/openassetio/Context.hpp
  src/openassetio-core/include/openassetio/TraitsData.hpp
  src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp
  src/openassetio-core/include/openassetio/hostApi/Manager.hpp
  src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp
  src/openassetio-core/include/openassetio/hostApi/ManagerImplementationFactoryInterface.hpp
  src/openassetio-core/include/openassetio/log/ConsoleLogger.hpp
  src/openassetio-core/include/openassetio/log/LoggerInterface.hpp
  src/openassetio-core/include/openassetio/log/SeverityFilter.hpp
  src/openassetio-core/include/openassetio/managerApi/Host.hpp
  src/openassetio-core/include/openassetio/managerApi/HostSession.hpp
  src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
  src/openassetio-core/include/openassetio/managerApi/ManagerStateBase.hpp
  src/openassetio-core/include/openassetio/typedefs.hpp
  src/openassetio-core/tests/CMakeLists.txt
  src/openassetio-core/tests/typedefsTest.cpp
  src/openassetio-python/bridge/CMakeLists.txt
  src/openassetio-python/bridge/include/openassetio/python/converter.hpp
  src/openassetio-python/bridge/src/python/converter.cpp
  src/openassetio-python/cmodule/src/EntityReferenceBinding.cpp
  src/openassetio-python/tests/bridge/CMakeLists.txt
  src/openassetio-python/tests/bridge/lsan_suppressions.txt
  src/openassetio-python/tests/bridge/python/test_converter.cpp
  src/openassetio-python/tests/package/hostApi/test_manager.py
  src/openassetio-python/tests/package/test_entityreference.py
Labels: feature branch

#950 [Examples] De-couple simpleResolver tests from BAL
  examples/host/simpleResolver/test_simpleResolver.py
Labels: test
