Repository OpenAssetIO/OpenAssetIO, pull requests merged in 2023-03, with the labels that each got.

#819 [Docs] Add notes on expected Code Review checks
  doc/contributing/CODE_REVIEWS.md
Labels: documentation

#824 [Doc] Add DR for method overload naming
  doc/decisions/DR015-Strategy-for-methods-with-several-signature-variations.md
Labels: decision record

#833 [Docs] Add notes on PyPi aarch64 support
  README.md
Labels: documentation

#830 Fix for minor typos
  doc/doxygen/src/EntitiesTraitsSpecifications.dox
Labels: documentation

#839 Update `simpleResolver` and docs with best practices
  RELEASE_NOTES.md
  examples/host/simpleResolver/README.md
  examples/host/simpleResolver/simpleResolver.py
Labels: documentation, examples

#861 [CI] Fix docs build artifact path
  .github/workflows/test.yml
Labels: ci
